
modLoader = "javafml"
loaderVersion = "${loader_version_range}"

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}-common.mixins.json"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon = "supplementaries:globe" #catalogue icon

[[dependencies.${mod_id}]]
    modId = "forge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_min_version},${minecraft_max_version})"
    ordering = "NONE"
    side = "CLIENT"





[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "Supplementaries"
    logoFile = "icon.png"
    authors = "MehVahdJukaar, Plantkillable"
    credits = "Put a book named 'credits' inside a notice board"

    updateJSONURL = "https://raw.githubusercontent.com/MehVahdJukaar/Supplementaries/1.20/forge/update.json"
    modUrl = "https://www.curseforge.com/minecraft/mc-mods/supplementaries"

    description = '''Many functional and useful Vanilla+ blocks'''

[modproperties.supplementaries]
    catalogueItemIcon = "supplementaries:globe" #catalogue icon
    configuredBackground = "supplementaries:textures/block/blackstone_tiles.png"

[[dependencies.supplementaries]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.0.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "moonlight"
    mandatory = true
    versionRange = "[${required_moonlight_version},]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.19-1.2.0,]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "quark"
    mandatory = false
    versionRange = "[1.19-3.4-404,]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "rubidium"
    mandatory = false
    versionRange = "[0.6.0,)"
    ordering = "NONE"
    side = "BOTH"

