modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MehVahdJukaar/Supplementaries/issues"

license = "ARR"

[[mods]]
    modId = "supplementaries"
    version = "${version}"
    displayName = "Supplementaries"
    logoFile = "icon.png"
    authors = "MehVahdJukaar, Plantkillable"
    credits = "Put a book named 'credits' inside a notice board"

    updateJSONURL = "https://raw.githubusercontent.com/MehVahdJukaar/Supplementaries/1.20/forge/update.json"
    modUrl = "https://www.curseforge.com/minecraft/mc-mods/supplementaries"

    description = '''Many functional and useful Vanilla+ blocks'''

[modproperties.supplementaries]
    catalogueItemIcon = "supplementaries:globe" #catalogue icon
    configuredBackground = "supplementaries:textures/block/blackstone_tiles.png"

[[dependencies.supplementaries]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.0.19,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "moonlight"
    mandatory = true
    versionRange = "[${required_moonlight_version},]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.19-1.2.0,]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "quark"
    mandatory = false
    versionRange = "[1.19-3.4-395,]"
    ordering = "AFTER"
    side = "BOTH"

