modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/MehVahdJukaar/Supplementaries/issues" #optional

license = "ARR"


[[mods]]
modId = "supplementaries"
version = "${version}"
displayName = "Supplementaries"


credits = "Put a book named 'credits' inside a notice board" #optional

updateJSONURL = "https://raw.githubusercontent.com/MehVahdJukaar/Supplementaries/master/forge/update.json"
modUrl = "https://www.curseforge.com/minecraft/mc-mods/supplementaries" #optional

authors = "MehVahdJukaar, Plantkillable" #optional

description = '''Many functional and useful Vanilla+ blocks'''

itemIcon = "supplementaries:globe" #catalogue icon

configuredBackground = "supplementaries:textures/blocks/blackstone_tiles.png"

logoFile = "icon.png" #optional

[[dependencies.supplementaries]]
    modId = "forge"
    mandatory = true
    versionRange = "[41.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "moonlight"
    mandatory = true
    versionRange = "[1.19.2-2.0.28,]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.supplementaries]]
    modId = "farmersdelight"
    mandatory = false
    versionRange = "[1.19-1.2.0,]"
    ordering = "NONE"
    side = "BOTH"

