
modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues" #optional

[[mods]] #mandatory

modId="supplementaries" #mandatory

version="1.16.5-0.9.25" #mandatory

displayName="Supplementaries" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries" #optional

logoFile="logo.png" #optional

credits="see curse forge page" #optional

authors="MehVahdJukaar" #optional

description='''Many functional and useful Vanilla+ blocks'''

[[dependencies.supplementaries]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17]"
    ordering="NONE"
    side="BOTH"
