
modLoader="javafml" #mandatory

loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues" #optional

[[mods]] #mandatory

modId="supplementaries" #mandatory

version="1.1.3" #mandatory

displayName="Supplementaries" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries" #optional

logoFile="logo.png" #optional

credits="Put a book named 'credits' inside a notice board" #optional

authors="MehVahdJukaar, Plantkillable" #optional

description='''Many functional and useful Vanilla+ blocks'''

itemIcon="supplementaries:globe" #catalogue icon

configuredBackground= "supplementaries:textures/blocks/blackstone_tiles.png"

[[dependencies.supplementaries]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38.0.14,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="selene"
    mandatory=true
    versionRange="[1.18-1.11,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="configured"
    mandatory=false
    versionRange="[1.5.0,)"
    ordering="NONE"
    side="CLIENT"
