
modLoader="javafml" #mandatory

loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://github.com/MehVahdJukaar/Supplementaries/issues" #optional

[[mods]] #mandatory

modId="supplementaries" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Supplementaries" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries" #optional

logoFile="logo.png" #optional

credits="Put a book named 'credits' inside a notice board" #optional

authors="MehVahdJukaar, Plantkillable" #optional

description='''Many functional and useful Vanilla+ blocks'''

itemIcon="supplementaries:globe" #catalogue icon

configuredBackground= "supplementaries:textures/blocks/blackstone_tiles.png"

[[dependencies.supplementaries]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.0.36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="selene"
    mandatory=true
    versionRange="[1.18.2-1.17.5,]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="configured"
    mandatory=false
    versionRange="[1.5.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.supplementaries]]

    modId="create"
    mandatory=false
    versionRange="[0.4c,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="flywheel"
    mandatory=false
    versionRange="[0.5.1,)"
    ordering="NONE"
    side="CLIENT"


