
modLoader="javafml" #mandatory

loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries/issues" #optional

[[mods]] #mandatory

modId="supplementaries" #mandatory

version="0.18.3" #mandatory

displayName="Supplementaries" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/supplementaries" #optional

logoFile="logo.png" #optional

credits="Put a book named 'credits' inside a notice board" #optional

authors="MehVahdJukaar, Plantkillable" #optional

description='''Many functional and useful Vanilla+ blocks'''

itemIcon="supplementaries:globe" #catalogue icon

configuredBackground= "supplementaries:textures/blocks/blackstone_tiles.png"

[[dependencies.supplementaries]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17]"
    ordering="NONE"
    side="BOTH"


[[dependencies.supplementaries]]

    modId="computercraft"
    mandatory=false
    versionRange="[1.99.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.supplementaries]]

modId="flywheel"
    mandatory=false
    versionRange="[1.16-0.2.3,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.supplementaries]]

    modId="configured"
    mandatory=false
    versionRange="[1.5.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.supplementaries]]

    modId="custom-villager-trades"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.supplementaries]]

    modId="selene"
    mandatory=true
    versionRange="[1.16.5-1.0,]"
    ordering="NONE"
    side="BOTH"
