name: Report Bug
description: "Found a bug? Report it."
title: "[🐞]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        BUG

- type: checkboxes
  id: pre-report-bug
  attributes:
    label: "Before Continuing:"
    options:
      - label: "Always check you are using the latest version of these mods and their dependencies"
        required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: The Version of Minecraft?
      options:
        - 1.20.1-FORGE
        - 1.20.1-FABRIC
        - 1.19.2-FORGE
        - 1.19.2-FABRIC
        - 1.18.2-FORGE
      default: 0
    validations:
      required: true
      
  - type: input
    id: supplementaries
    attributes:
      label: EveryCompat Version
      description: The current version of EveryCompat
      placeholder: ex. supplementaries-1.20-2.7.33
    validations:
      required: true
     
  - type: input
    id: moonlight
    attributes:
      label: Moonlight Lib Version
      description: The current version of Moonlight Lib
      placeholder: ex. moonlight-1.20-2.8.46-forge
    validations:
      required: true

  - type: textarea
    id: issue-details
    attributes:
      label: "Issue Detail"
      description: "A clear and concise description of what the bug is."
      placeholder: "ATTENTION: Always include A log if the issue is causing a crash. These are found in your instance directory under /logs \nTIP: If applicable, add screenshots to help explain your problem.\nTIP: You can drag the latest.log file in here."
    validations:
        required: true
